server:
     port: 8081
     
spring:
  cloud:
    config:
      uri: "http://localhost:8888"
    
rating:
    data:
      service:
          url: "http://rating-data-service/rating/user/"
          
movie:
   info:
     service:
          url: "http://movie-info-service/movieInfo/"
   overview1: "A group of juvenile delinquents lives a criminal, violent life in the festering slums of Mexico City, 
   among them the young Pedro, whose morality is gradually corrupted and destroyed by the others."
   overview2: "Schnitzel Paradise is a Dutch film about a young 
   Moroccan man working in the kitchen of popular Dutch restaurant."
   
management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  greeting: how are you!
  msg: hello benzema ${app.greeting}
  list:
    values: Kelly Brook,Julia Ann,Chopa,Doto
  dbValues: "{connection_string: 'jdbc:oracle:thin@localhost:1521:orcl',username: '${con.username}',password: '${con.password}'}"

con:
  username: HR
  password: "{cipher}1eba7461934dcc731f9890b42af37295e856fe1a9d2171ae66ce405c635f71e3"
  


