spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
    username: ASSIGNDB
    password: 14292
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
server:
  port: 9090     
